<?php

use App\Http\Controllers\CalculateController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PSUController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentMgmt\StudentsController;
use Illuminate\Support\Facades\Route;

// / Auto Generated by Laravel and Breeze Auth
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

// Recitation
Route::get('/add', [CalculateController::class, 'add'])->name('calculate.add');
Route::get('/subtract', [CalculateController::class, 'subtract'])->name('calculate.store');
Route::get('/multiply', [CalculateController::class, 'multiply'])->name('calculate.multiply');
Route::get('/divide', [CalculateController::class, 'divide'])->name('calculate.divide');
Route::get('/modulo', [CalculateController::class, 'modulo'])->name('calculate.modulo');

Route::resource('/clients', ClientController::class);

Route::get('/welcome/{author}/{systemName}', [PSUController::class, 'welcome'])->name('welcome');
Route::get('/mission', [PSUController::class, 'mission'])->name('mission');
Route::get('/vision', [PSUController::class, 'vision'])->name('vision');
Route::get('/EOMSPolicy', [PSUController::class, 'EOMSPolicy'])->name('EOMSPolicy');

Route::get('/student/{name}/{course}', [PSUController::class, 'student'])->name('student');

Route::resource('/students', StudentController::class);

Route::get('/greetings', [ClientController::class, 'displayGreetings'])->name('greetings');

Route::get('/dashboard', function () {
    return view('client.dashboard');
})->name('dashboard');
Route::get('/about', function () {
    return view('client.aboutUs');
})->name('about');
Route::get('/profile', function () {
    return view('client.profile');
})->name('profile');

Route::get('/studentMgmtHome', [StudentsController::class, 'displayHome'])->name('studentMgmtHome');

Route::get('/studentMgmtStudents', [StudentsController::class, 'displayStudents'])->name('studentMgmtStudents');

Route::get('/studentMgmtAbout', [StudentsController::class, 'displayAbout'])->name('studentMgmtAbout');
