<?php

use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\CalculateController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PSUController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentMgmt\CoursesController;
use App\Http\Controllers\StudentMgmt\DegreesController;
use App\Http\Controllers\StudentMgmt\StudentsController;
use App\Http\Controllers\StudentMgmt\UserProfileController;
use Illuminate\Support\Facades\Route;

// / Auto Generated by Laravel and Breeze Auth
// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');
// Recitation
Route::get('/add', [CalculateController::class, 'add'])->name('calculate.add');
Route::get('/subtract', [CalculateController::class, 'subtract'])->name('calculate.store');
Route::get('/multiply', [CalculateController::class, 'multiply'])->name('calculate.multiply');
Route::get('/divide', [CalculateController::class, 'divide'])->name('calculate.divide');
Route::get('/modulo', [CalculateController::class, 'modulo'])->name('calculate.modulo');

Route::resource('/clients', ClientController::class);

Route::get('/welcome/{author}/{systemName}', [PSUController::class, 'welcome'])->name('welcome');
Route::get('/mission', [PSUController::class, 'mission'])->name('mission');
Route::get('/vision', [PSUController::class, 'vision'])->name('vision');
Route::get('/EOMSPolicy', [PSUController::class, 'EOMSPolicy'])->name('EOMSPolicy');

Route::get('/student/{name}/{course}', [PSUController::class, 'student'])->name('student');

Route::resource('/students', StudentController::class);

Route::get('/greetings', [ClientController::class, 'displayGreetings'])->name('greetings');

// Route::get('/', function () {
//    return view('client.dashboard');
// })->name('dashboard')->middleware('maintenance');

Route::get('/about', function () {
    return view('client.aboutUs');
})->name('about');
Route::get('/client-profile', function () {
    return view('client.profile');
})->name('client.profile');

Route::resource('/degrees', DegreesController::class);

Route::resource('/courses', CoursesController::class);

Route::resource('/user-profiles', UserProfileController::class);

Route::get('/studentMgmtHome', [StudentsController::class, 'displayHome'])
    ->name('studentMgmtHome')
    ->middleware('maintenance');

Route::get('/maintenance', function () {
    return view('maintenance');
})->name('maintenance');

Route::middleware('group_middleware')->group(function () {

    Route::get('/studentMgmtStudents', [StudentsController::class, 'displayStudents'])->name('studentMgmtStudents');

    Route::get('/studentMgmtAbout', [StudentsController::class, 'displayAbout'])->name('studentMgmtAbout');

    Route::resource('/studentMgmt', StudentsController::class);
});

Route::get('/register', function () {
    return view('auth.register');
})->name('register');

Route::get('/', [UserController::class, 'login'])->name('login')->middleware('maintenance');
Route::get('/updatePasswordPage', [UserController::class, 'showUpdatePasswordForm'])->name('password.update.page');
Route::post('/login', [UserController::class, 'authenticate'])->name('login.authenticate');
Route::put('/passwordUpdate', [UserController::class, 'updatePassword'])->name('password.update');

Route::get('/studentSettings', function () {
    return view('student_mgmt.settings');
})->name('studentSettings');

Route::get('/register', [UserController::class, 'registerPage'])->name('register')->middleware('maintenance');
Route::post('/registerUser', [UserController::class, 'register'])->name('register.user')->middleware('maintenance');

Route::get('/studentDashboard/{id}', [StudentController::class, 'dashboard'])->name('studentDashboard')->middleware('maintenance');
